apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: default
data:
  prometheus.yml: |-    
    scrape_configs:
      - job_name: 'node-exporter'

        static_configs:
          - targets: ['10.44.10.44:80']
